blueprint:
  name: Szablon wyłączenia światła – multiświatło i bez czujnika
  description: |
    Wyłącza jedno lub więcej świateł po określonym czasie od ostatniego ruchu – lub po czasie bez względu na ruch.
    Obsługuje 1–3 źródła światła i 0–2 czujniki ruchu. Powiadomienia opcjonalne.
  domain: automation
  input:
    motion_sensor_1:
      name: Czujnik ruchu 1 (opcjonalnie)
      default: []
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    motion_sensor_2:
      name: Czujnik ruchu 2 (opcjonalnie)
      default: []
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    light_1:
      name: Światło 1
      selector:
        entity:
          domain: light

    light_2:
      name: Światło 2 (opcjonalnie)
      default: []
      selector:
        entity:
          domain: light

    light_3:
      name: Światło 3 (opcjonalnie)
      default: []
      selector:
        entity:
          domain: light

    delay_minutes:
      name: Opóźnienie (w minutach)
      default: 10
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: minutes
          mode: slider

    send_notification:
      name: Wyślij powiadomienie
      default: false
      selector:
        boolean: {}

    notify_target:
      name: Usługa powiadomień (np. notify.mobile_app_pixel_7)
      default: ""
      selector:
        text:
          type: text

    notify_target_2:
      name: Druga usługa powiadomień (opcjonalnie)
      default: ""
      selector:
        text:
          type: text

trigger:
  - platform: state
    entity_id: !input motion_sensor_1
    to: "off"
    for:
      minutes: !input delay_minutes
  - platform: state
    entity_id: !input motion_sensor_2
    to: "off"
    for:
      minutes: !input delay_minutes
  - platform: time_pattern
    minutes: "/1"  # sprawdza co minutę, jeśli brak czujników

condition:
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ not (motion_sensor_1 or motion_sensor_2) }}"
      - condition: and
        conditions:
          - condition: state
            entity_id: !input motion_sensor_1
            state: "off"
          - condition: state
            entity_id: !input motion_sensor_2
            state: "off"

  - condition: or
    conditions:
      - condition: state
        entity_id: !input light_1
        state: "on"
      - condition: template
        value_template: "{{ (light_2 != [] and is_state(light_2, 'on')) or (light_3 != [] and is_state(light_3, 'on')) }}"

action:
  - variables:
      notify1: !input notify_target
      notify2: !input notify_target_2
      notify_enabled: !input send_notification
      delay: !input delay_minutes
      light_1: !input light_1
      light_2: !input light_2
      light_3: !input light_3

  - service: light.turn_off
    target:
      entity_id:
        - !input light_1
        - !input light_2
        - !input light_3

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ notify_enabled and notify1 != '' }}"
        sequence:
          - service: "{{ notify1 }}"
            data:
              message: >-
                Światła zostały wyłączone po {{ delay }} minutach braku ruchu lub po czasie.

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ notify2 != '' }}"
                sequence:
                  - service: "{{ notify2 }}"
                    data:
                      message: >-
                        (Kopia) Światła zostały wyłączone automatycznie.

      - conditions:
          - condition: template
            value_template: "{{ true }}"
        sequence:
          - service: persistent_notification.create
            data:
              title: "Blueprint INFO"
              message: >-
                Wyłączono światła. Powiadomienia: {{ 'TAK' if notify_enabled else 'NIE' }}

mode: restart
