blueprint:
  name: Proste wyłączenie oświetlenia po bezruchu (1–3 źródła, 1–2 czujniki, czas w minutach)
  description: >
    Wyłącza jedno, dwa lub trzy wskazane oświetlenia po czasie bezruchu
    wykrytym przez jeden lub dwa czujniki ruchu. Czas podawany w minutach.
  domain: automation
  author: szpila86
  source_url: https://github.com/sza86/BluePrints/edit/main/szablon_wylaczenia_swiatla.yaml

  input:
    # Obowiązkowy czujnik ruchu
    motion_sensor_1:
      name: Czujnik ruchu #1 (obowiązkowy)
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    # Opcjonalny drugi czujnik ruchu
    motion_sensor_2:
      name: Czujnik ruchu #2 (opcjonalny)
      default: []
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    # Główne światło (wymagane)
    light_target_1:
      name: Główne oświetlenie (obowiązkowe)
      selector:
        entity:
          domain: light

    # Dodatkowe światło 1 (opcjonalne)
    light_target_2:
      name: Dodatkowe oświetlenie #1 (opcjonalne)
      default: []
      selector:
        entity:
          domain: light
          multiple: false

    # Dodatkowe światło 2 (opcjonalne)
    light_target_3:
      name: Dodatkowe oświetlenie #2 (opcjonalne)
      default: []
      selector:
        entity:
          domain: light
          multiple: false

    # Czas bezruchu w minutach
    delay_time:
      name: Czas bezruchu (minuty)
      default: 1
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes
          mode: slider

# Tryb restart – każde nowe wykrycie ruchu restartuje timer
mode: restart
# Milczące przekroczenie limitów wykonania
max_exceeded: silent

# Wyzwalacze – oba czujniki (jeśli użyte) muszą być nieaktywne przez podany czas
trigger:
  - platform: state
    entity_id: !input motion_sensor_1
    to: 'off'
    for:
      minutes: !input delay_time  # używamy minut bez konwersji
  - platform: state
    entity_id: !input motion_sensor_2
    to: 'off'
    for:
      minutes: !input delay_time

# Zmienne pomocnicze do użycia w warunkach i akcjach
variables:
  motion_sensor_1: !input motion_sensor_1
  motion_sensor_2: !input motion_sensor_2
  light1: !input light_target_1
  light2: !input light_target_2
  light3: !input light_target_3

# Warunek: brak ruchu na czujniku 1 i (jeśli obecny) czujniku 2
condition:
  - condition: template
    value_template: >
      {{ is_state(motion_sensor_1, 'off') and
         (motion_sensor_2 == [] or is_state(motion_sensor_2, 'off')) }}

# Akcje: wyłącz każde aktywne światło + zapisz do logbooka
action:
  # Wyłączenie światła 1 jeśli jest włączone
  - choose:
      - conditions: "{{ is_state(light1, 'on') }}"
        sequence:
          - service: logbook.log
            data:
              name: Automatyzacja oświetlenia
              message: "Wyłączono {{ light1 }} po wykryciu braku ruchu."
              entity_id: "{{ light1 }}"
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ light1 }}"

  # Wyłączenie światła 2 jeśli zdefiniowane i włączone
  - choose:
      - conditions: "{{ light2 != [] and is_state(light2, 'on') }}"
        sequence:
          - service: logbook.log
            data:
              name: Automatyzacja oświetlenia
              message: "Wyłączono {{ light2 }} po wykryciu braku ruchu."
              entity_id: "{{ light2 }}"
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ light2 }}"

  # Wyłączenie światła 3 jeśli zdefiniowane i włączone
  - choose:
      - conditions: "{{ light3 != [] and is_state(light3, 'on') }}"
        sequence:
          - service: logbook.log
            data:
              name: Automatyzacja oświetlenia
              message: "Wyłączono {{ light3 }} po wykryciu braku ruchu."
              entity_id: "{{ light3 }}"
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ light3 }}"
